app:
  encryption:
    password: "1234"
    type: aesGsmEncryptor #it could be noneEncryptor, springSecurityBytesEncryptor, aesGsmEncryptor or springSecurityTextEncryptor

  stock-quote-api:
    url: https://gd5tqp34ng.execute-api.us-east-2.amazonaws.com/default/GetStockQuote/{symbol}

  redis:
    ttl-seconds: 3600

#logging:
#  file: application.log
#  level:
#    com:
#      example:
#        stockquotespring: INFO


info:
  app:
    name: stock-quote
    description: Stock Quote microservice

management:
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /health

